# Release configuration for GoReleaser
project_name: code-mage

before:
  hooks:
    # Ensure the Go module is tidy and dependencies are downloaded
    - go mod tidy
    - go mod download

builds:
  - id: code-mage
    main: ./cmd/code-mage
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    env:
      - CGO_ENABLED=0
    binary: code-mage

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
    name: ${{ github.event.repository.name }}

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"

checksum:
  name_template: 'checksums.txt'


