name: Build and Create Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Specify the Ruby version

    - name: Install Asciidoctor and Extensions
      run: |
        gem install asciidoctor
        gem install asciidoctor-pdf
        gem install asciidoctor-epub3
        gem install pygments.rb

    - name: Read Version File
      id: read_version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build PDF
      run: ./build pdf

    - name: Build EPUB
      run: ./build epub

    - name: Build HTML
      run: ./build html

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: artifacts/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        release_name: "Release ${{ env.VERSION }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/code-mage-book-*.pdf
        asset_name: code-mage-book.pdf
        asset_content_type: application/pdf

    - name: Upload EPUB to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/code-mage-book-*.epub
        asset_name: code-mage-book.epub
        asset_content_type: application/epub+zip

